@baseUrl = http://localhost:3000

### Requests requiring authorization
### Login as user
# @name user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### Get user
GET {{baseUrl}}/users/{{user.response.body.id}}
Content-Type: application/json
Authorization: {{user.response.body.token}}

### Get user progress
POST {{baseUrl}}/users/getProgress
Content-Type: application/json
Authorization: {{user.response.body.token}}

{
	"cours": "c"
}

### Set user progress
POST {{baseUrl}}/users/setProgress
Content-Type: application/json
Authorization: {{user.response.body.token}}

{
	"cours": "c",
	"progres": 50
}

### Get user avatar
GET {{baseUrl}}/users/{{user.response.body.id}}/avatar
